# Generated by Django 5.1.2 on 2025-10-24 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
                ('icon', models.FileField(blank=True, null=True, upload_to='moto_categories/icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория мотоцикла',
                'verbose_name_plural': 'Категории мотоциклов',
            },
        ),
        migrations.CreateModel(
            name='MotoFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название особенности')),
            ],
            options={
                'verbose_name': 'Особенность мотоцикла',
                'verbose_name_plural': 'Особенности мотоциклов',
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('engine_volume', models.FloatField(verbose_name='Объем двигателя (см³)')),
                ('mileage', models.IntegerField(verbose_name='Пробег (км)')),
                ('transmission', models.CharField(blank=True, max_length=50, verbose_name='Коробка передач')),
                ('oil_type', models.CharField(choices=[('Бензин', 'Бензин'), ('Электричество', 'Электричество')], max_length=20, verbose_name='Тип топлива')),
                ('bike_type', models.CharField(blank=True, max_length=50, verbose_name='Тип мотоцикла')),
                ('power', models.IntegerField(blank=True, null=True, verbose_name='Мощность (л.с.)')),
                ('price_per_day', models.IntegerField(verbose_name='Цена за день ($)')),
                ('deposit', models.IntegerField(verbose_name='Депозит ($)')),
                ('status', models.CharField(choices=[('available', 'Свободен'), ('booked', 'Забронирован')], default='available', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycles.motocategory', verbose_name='Категория')),
                ('features', models.ManyToManyField(blank=True, to='motorcycles.motofeature', verbose_name='Особенности')),
            ],
            options={
                'verbose_name': 'Мотоцикл',
                'verbose_name_plural': 'Мотоциклы',
            },
        ),
        migrations.CreateModel(
            name='MotoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='motorcycles/images/')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='motorcycles.motorcycle')),
            ],
            options={
                'verbose_name': 'Фотография мотоцикла',
                'verbose_name_plural': 'Фотографии мотоциклов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MotoBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус брони')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycles.motorcycle', verbose_name='Мотоцикл')),
            ],
            options={
                'verbose_name': 'Бронирование мотоцикла',
                'verbose_name_plural': 'Бронирования мотоциклов',
            },
        ),
    ]
