# Generated by Django 5.1.2 on 2025-10-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motobooking',
            name='client_name',
            field=models.CharField(default='bro', max_length=200, verbose_name='Имя клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motobooking',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='motobooking',
            name='phone_number',
            field=models.CharField(default='654', max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
