# Generated by Django 5.1.2 on 2025-10-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0002_motobrand_motorcycle_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель'),
        ),
    ]
