# Generated by Django 4.2.7 on 2025-10-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0002_motobooking_client_name_motobooking_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motobooking',
            name='user',
        ),
        migrations.AddField(
            model_name='motobooking',
            name='telegram_id',
            field=models.CharField(default='dghd', max_length=100, verbose_name='Telegram ID'),
            preserve_default=False,
        ),
    ]
