# Generated by Django 5.1.2 on 2025-10-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0004_motomodel_alter_motorcycle_model'),
    ]

    operations = [
    ]
