# Generated by Django 5.1.2 on 2025-10-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('motorcycles', '0005_auto_20251026_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='motobooking',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='motobooking',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='motobooking',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deliveryzone', verbose_name='Зона доставки'),
        ),
        migrations.AddField(
            model_name='motobooking',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Депозит'),
        ),
        migrations.AddField(
            model_name='motobooking',
            name='provider_terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Согласие с правилами прокатчика'),
        ),
        migrations.AddField(
            model_name='motobooking',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость аренды'),
        ),
        migrations.AddField(
            model_name='motobooking',
            name='service_terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Согласие с правилами сервиса'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='delivery_zones',
            field=models.ManyToManyField(blank=True, to='core.deliveryzone', verbose_name='Доступные зоны доставки'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='rental_provider',
            field=models.ForeignKey(blank=True, help_text='Прокатчик, которому принадлежит мотоцикл', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rentalprovider', verbose_name='Прокатчик'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='price_per_day',
            field=models.IntegerField(help_text='Базовая цена, используется если не заданы тарифы', verbose_name='Цена за день ($) (базовая)'),
        ),
        migrations.CreateModel(
            name='MotoPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_days', models.IntegerField(help_text='Минимальное количество дней для применения тарифа', verbose_name='Минимум дней')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за день ($)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='motorcycles.motorcycle', verbose_name='Мотоцикл')),
            ],
            options={
                'verbose_name': 'Ценовой тариф мотоцикла',
                'verbose_name_plural': 'Ценовые тарифы мотоциклов',
                'ordering': ['motorcycle', 'min_days'],
                'unique_together': {('motorcycle', 'min_days')},
            },
        ),
    ]
