# Generated by Django 5.1.2 on 2025-10-28 07:44

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0006_motobooking_city_motobooking_delivery_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motobrand',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='motorcycles/brands/icons/', validators=[core.validators.validate_icon_file], verbose_name='Иконка марки'),
        ),
        migrations.AlterField(
            model_name='motocategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='moto_categories/icons/', validators=[core.validators.validate_icon_file], verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='motomodel',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='motorcycles/models/icons/', validators=[core.validators.validate_icon_file], verbose_name='Иконка модели'),
        ),
    ]
