# Generated by Django 5.1.2 on 2025-10-24 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('year', models.IntegerField(verbose_name='Год постройки')),
                ('floors', models.IntegerField(default=1, verbose_name='Количество этажей')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('area', models.FloatField(verbose_name='Площадь (м²)')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('price_per_day', models.IntegerField(verbose_name='Цена за день ($)')),
                ('deposit', models.IntegerField(verbose_name='Депозит ($)')),
                ('status', models.CharField(choices=[('available', 'Свободен'), ('booked', 'Забронирован')], default='available', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='HouseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
                ('icon', models.FileField(blank=True, null=True, upload_to='house_categories/icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория дома',
                'verbose_name_plural': 'Категории домов',
            },
        ),
        migrations.CreateModel(
            name='HouseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название особенности')),
            ],
            options={
                'verbose_name': 'Особенность дома',
                'verbose_name_plural': 'Особенности домов',
            },
        ),
        migrations.CreateModel(
            name='HouseBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата заезда')),
                ('end_date', models.DateField(verbose_name='Дата выезда')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус брони')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('guests', models.IntegerField(default=1, verbose_name='Количество гостей')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house', verbose_name='Дом')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование дома',
                'verbose_name_plural': 'Бронирования домов',
            },
        ),
        migrations.AddField(
            model_name='house',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.housecategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='house',
            name='features',
            field=models.ManyToManyField(blank=True, to='houses.housefeature', verbose_name='Особенности'),
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses/images/')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='houses.house')),
            ],
            options={
                'verbose_name': 'Фотография дома',
                'verbose_name_plural': 'Фотографии домов',
                'ordering': ['order'],
            },
        ),
    ]
