# Generated by Django 5.1.2 on 2025-10-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='address',
        ),
        migrations.RemoveField(
            model_name='house',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='house',
            name='year',
        ),
    ]
