# Generated by Django 5.1.2 on 2025-10-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_remove_house_address_remove_house_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housebooking',
            name='guests',
        ),
        migrations.AddField(
            model_name='housebooking',
            name='client_name',
            field=models.CharField(default='ibro', max_length=200, verbose_name='Имя клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housebooking',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='housebooking',
            name='phone_number',
            field=models.CharField(default='788', max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
