# Generated by Django 4.2.7 on 2025-10-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_remove_housebooking_guests_housebooking_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housebooking',
            name='user',
        ),
        migrations.AddField(
            model_name='housebooking',
            name='telegram_id',
            field=models.CharField(default='dgh', max_length=100, verbose_name='Telegram ID'),
            preserve_default=False,
        ),
    ]
