# Generated by Django 5.1.2 on 2025-10-24 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название экскурсии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('duration', models.CharField(choices=[('2_hours', '2 часа'), ('4_hours', '4 часа'), ('6_hours', '6 часов'), ('full_day', 'Полный день'), ('multi_day', 'Несколько дней')], max_length=20, verbose_name='Продолжительность')),
                ('days_available', models.CharField(help_text='Например: Пн, Ср, Пт или Ежедневно', max_length=100, verbose_name='Дни проведения')),
                ('meeting_point', models.CharField(blank=True, max_length=200, verbose_name='Место встречи')),
                ('max_participants', models.IntegerField(default=10, verbose_name='Максимальное количество участников')),
                ('price_per_person', models.IntegerField(verbose_name='Цена за человека ($)')),
                ('child_price', models.IntegerField(blank=True, null=True, verbose_name='Цена для детей ($)')),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('booked', 'Забронирована')], default='available', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
            },
        ),
        migrations.CreateModel(
            name='ExcursionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория экскурсии',
                'verbose_name_plural': 'Категории экскурсий',
            },
        ),
        migrations.CreateModel(
            name='ExcursionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название особенности')),
            ],
            options={
                'verbose_name': 'Особенность экскурсии',
                'verbose_name_plural': 'Особенности экскурсий',
            },
        ),
        migrations.CreateModel(
            name='ExcursionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Дата экскурсии')),
                ('participants', models.IntegerField(default=1, verbose_name='Количество участников')),
                ('children', models.IntegerField(default=0, verbose_name='Количество детей')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус брони')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('special_requests', models.TextField(blank=True, verbose_name='Особые пожелания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excursions.excursion', verbose_name='Экскурсия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование экскурсии',
                'verbose_name_plural': 'Бронирования экскурсий',
            },
        ),
        migrations.AddField(
            model_name='excursion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excursions.excursioncategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='features',
            field=models.ManyToManyField(blank=True, to='excursions.excursionfeature', verbose_name='Особенности'),
        ),
        migrations.CreateModel(
            name='ExcursionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='excursions/images/')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='excursions.excursion')),
            ],
            options={
                'verbose_name': 'Фотография экскурсии',
                'verbose_name_plural': 'Фотографии экскурсий',
                'ordering': ['order'],
            },
        ),
    ]
