# Generated by Django 5.1.2 on 2025-10-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='child_price',
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='days_available',
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='meeting_point',
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='excursionbooking',
            name='children',
        ),
        migrations.AddField(
            model_name='excursioncategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='excursion_categories/icons/', verbose_name='Иконка'),
        ),
    ]
