# Generated by Django 5.1.2 on 2025-10-24 11:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0002_remove_excursion_child_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursionbooking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='excursionbooking',
            name='special_requests',
        ),
        migrations.AddField(
            model_name='excursion',
            name='days',
            field=models.IntegerField(default=1, verbose_name='Количество дней'),
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='client_name',
            field=models.CharField(default='Unknown', max_length=200, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='phone_number',
            field=models.CharField(default='Не указан', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='excursionbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='excursionbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Telegram'),
        ),
    ]
