# Generated by Django 4.2.7 on 2025-10-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0003_remove_excursionbooking_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursionbooking',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='excursionbooking',
            name='user',
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='telegram_id',
            field=models.CharField(default='fdh', max_length=100, verbose_name='Telegram ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='excursionbooking',
            name='client_name',
            field=models.CharField(max_length=200, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='excursionbooking',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='excursionbooking',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='excursionbooking',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='excursionbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость'),
        ),
    ]
