# Generated by Django 5.1.2 on 2025-10-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('excursions', '0004_remove_excursionbooking_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='delivery_zones',
            field=models.ManyToManyField(blank=True, to='core.deliveryzone', verbose_name='Доступные зоны трансфера'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='deposit',
            field=models.IntegerField(default=0, verbose_name='Депозит ($)'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='rental_provider',
            field=models.ForeignKey(blank=True, help_text='Организатор экскурсии', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rentalprovider', verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deliveryzone', verbose_name='Зона трансфера'),
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Депозит'),
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='excursion_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость экскурсии'),
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='participants',
            field=models.IntegerField(default=1, verbose_name='Количество участников'),
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='provider_terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Согласие с правилами организатора'),
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='service_terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Согласие с правилами сервиса'),
        ),
        migrations.AddField(
            model_name='excursionbooking',
            name='transfer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость трансфера'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='price_per_person',
            field=models.IntegerField(help_text='Базовая цена, используется если не заданы тарифы', verbose_name='Цена за человека ($) (базовая)'),
        ),
        migrations.CreateModel(
            name='ExcursionPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_participants', models.IntegerField(help_text='Минимальное количество участников для применения тарифа', verbose_name='Минимум участников')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за человека ($)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='excursions.excursion', verbose_name='Экскурсия')),
            ],
            options={
                'verbose_name': 'Ценовой тариф экскурсии',
                'verbose_name_plural': 'Ценовые тарифы экскурсий',
                'ordering': ['excursion', 'min_participants'],
                'unique_together': {('excursion', 'min_participants')},
            },
        ),
    ]
