# Generated by Django 5.1.2 on 2025-10-28 07:45

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0005_excursion_city_excursion_delivery_zones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursioncategory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='excursion_categories/icons/', validators=[core.validators.validate_icon_file], verbose_name='Иконка'),
        ),
    ]
