# Generated by Django 5.1.2 on 2025-10-24 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('engine_volume', models.FloatField(verbose_name='Объем двигателя (л)')),
                ('mileage', models.IntegerField(verbose_name='Пробег (км)')),
                ('transmission', models.CharField(choices=[('AKПП', 'Автоматическая коробка передач'), ('МКПП', 'Механическая коробка передач'), ('Робот', 'Роботизированная коробка передач'), ('Вариатор', 'Вариаторная коробка передач')], max_length=20, verbose_name='Коробка передач')),
                ('oil_type', models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Гибрид', 'Гибрид'), ('Электричество', 'Электричество')], max_length=20, verbose_name='Тип топлива')),
                ('range_km', models.IntegerField(blank=True, null=True, verbose_name='Запас хода (км)')),
                ('price_per_day', models.IntegerField(verbose_name='Цена за день ($)')),
                ('price_per_3_days', models.IntegerField(blank=True, null=True, verbose_name='Цена за 3 дня ($)')),
                ('deposit', models.IntegerField(verbose_name='Депозит ($)')),
                ('status', models.CharField(choices=[('available', 'Свободен'), ('booked', 'Забронирован'), ('maintenance', 'На обслуживании')], default='available', max_length=20, verbose_name='Статус')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новое авто')),
                ('for_travel', models.BooleanField(default=False, verbose_name='Для путешествий')),
                ('no_prepayment', models.BooleanField(default=False, verbose_name='Без предоплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
                ('icon', models.FileField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус брони')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/images/')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'verbose_name': 'Фотография автомобиля',
                'verbose_name_plural': 'Фотографии автомобилей',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.category', verbose_name='Категория'),
        ),
    ]
