# Generated by Django 5.1.2 on 2025-10-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price_per_3_days',
        ),
        migrations.RemoveField(
            model_name='car',
            name='range_km',
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новое авто'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Свободен'), ('booked', 'Забронирован')], default='available', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=50, verbose_name='Коробка передач'),
        ),
    ]
