# Generated by Django 5.1.2 on 2025-10-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_price_per_3_days_remove_car_range_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название особенности')),
                ('icon', models.FileField(blank=True, null=True, upload_to='features/icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Особенность',
                'verbose_name_plural': 'Особенности',
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='for_travel',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='car',
            name='no_prepayment',
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(blank=True, to='cars.feature', verbose_name='Особенности'),
        ),
    ]
