# Generated by Django 5.1.2 on 2025-10-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_feature_remove_car_for_travel_remove_car_is_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='icon',
        ),
    ]
