# Generated by Django 5.1.2 on 2025-10-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carmodel_alter_car_model'),
    ]

    operations = [
    ]
