# Generated by Django 5.1.2 on 2025-10-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20251026_1254'),
    ]

    operations = [
    ]
