# Generated by Django 4.2.7 on 2025-10-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_booking_client_name_booking_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='telegram_id',
            field=models.CharField(default='121', max_length=100, verbose_name='Telegram ID'),
            preserve_default=False,
        ),
    ]
