# Generated by Django 5.1.2 on 2025-10-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20251026_1304'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deliveryzone', verbose_name='Зона доставки'),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Депозит'),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Согласие с правилами прокатчика'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость аренды'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Согласие с правилами сервиса'),
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='car',
            name='delivery_zones',
            field=models.ManyToManyField(blank=True, to='core.deliveryzone', verbose_name='Доступные зоны доставки'),
        ),
        migrations.AddField(
            model_name='car',
            name='rental_provider',
            field=models.ForeignKey(blank=True, help_text='Прокатчик, которому принадлежит автомобиль', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rentalprovider', verbose_name='Прокатчик'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.IntegerField(help_text='Базовая цена, используется если не заданы тарифы', verbose_name='Цена за день ($) (базовая)'),
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_days', models.IntegerField(help_text='Минимальное количество дней для применения тарифа', verbose_name='Минимум дней')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за день ($)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='cars.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Ценовой тариф',
                'verbose_name_plural': 'Ценовые тарифы',
                'ordering': ['car', 'min_days'],
                'unique_together': {('car', 'min_days')},
            },
        ),
    ]
