# Generated by Django 5.1.2 on 2025-10-28 07:44

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_booking_city_booking_delivery_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='cars/brands/icons/', validators=[core.validators.validate_icon_file], verbose_name='Иконка марки'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='cars/models/icons/', validators=[core.validators.validate_icon_file], verbose_name='Иконка модели'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='categories/icons/', validators=[core.validators.validate_icon_file], verbose_name='Иконка'),
        ),
    ]
